INSERT INTO courses(course_name ,
    course_code ,
    subjects_included ,
    teachers_assigned ,
    num_students_enrolled)








values('Robotics', 'ROBOTICS102', 'Advanced Robotics, Artificial Intelligence', 'Mr. Cooper, Ms. Stewart', 28),
('Public Speaking', 'PUBLIC_SPEAK102', 'Debate, Persuasive Speaking', 'Ms. King, Mr. White', 33),
('Graphic Design', 'GRAPHIC_DESIGN102', 'Digital Illustration, Motion Graphics', 'Ms. Hill, Mr. Adams', 40),
('Web Development', 'WEBDEV102', 'Backend Development, APIs', 'Mr. Turner, Ms. Parker', 45),
('Entrepreneurship', 'ENTREPRENEURSHIP102', 'Venture Capital, Innovation', 'Ms. King, Mr. White', 38),
('Yoga', 'YOGA102', 'Yoga Philosophy, Meditation', 'Ms. Martinez, Mr. Baker', 28),
('Engineering Design', 'ENG_DESIGN102', 'Product Design, CAD Modeling', 'Mr. Thompson, Ms. Lee', 32),
('Health Informatics', 'HEALTH_INFORMATICS102', 'Healthcare Data Management, Telemedicine', 'Ms. Baker, Mr. Scott', 35),
('Legal Studies', 'LEGAL_STUDIES102', 'Criminal Law, Civil Law', 'Ms. Stewart, Mr. Adams', 39),
('Film Studies', 'FILM_STUDIES102', 'Cinematography, Screenwriting', 'Mr. Nguyen, Ms. Hill', 43),
('Photography', 'PHOTOGRAPHY102', 'Digital Photography, Photo Editing', 'Ms. Parker, Mr. Turner', 31),
('Game Development', 'GAMEDEV102', 'Game Engines, Multiplayer Games', 'Mr. Cooper, Ms. King', 37),
('Medical Terminology', 'MEDTERM102', 'Medical Coding, Healthcare Terminology', 'Ms. Lee, Mr. Thompson', 42),
('Nutrition Science', 'NUTRITION_SCIENCE102', 'Dietary Supplements, Public Health Nutrition', 'Ms. Stewart, Mr. Adams', 36),
('Child Development', 'CHILD_DEVELOPMENT102', 'Adolescent Psychology, Parenting Skills', 'Ms. Baker, Mr. Scott', 40),
('Music Appreciation', 'MUSIC_APPRECIATION102', 'World Music, Jazz', 'Mr. Nguyen, Ms. Hill', 45),
('Creative Writing', 'CREATIVE_WRITING102', 'Screenwriting, Non-fiction Writing', 'Ms. Parker, Mr. Turner', 48),
('Physical Therapy', 'PHYSICAL_THERAPY102', 'Orthopedic Physical Therapy, Sports Rehabilitation', 'Ms. King, Mr. White', 32),
('Art History', 'ART_HISTORY102', 'Baroque Art, Contemporary Art', 'Mr. Thompson, Ms. Lee', 38),
('Interior Design', 'INTERIOR_DESIGN102', 'Residential Design, Commercial Design', 'Ms. Stewart, Mr. Adams', 36),
('Drama', 'DRAMA101', 'Acting Techniques, Theater Production', 'Ms. Powell, Mr. Turner', 35),
('Fashion Merchandising', 'FASHION_MERCH101', 'Retail Buying, Fashion Forecasting', 'Ms. Stewart, Mr. Adams', 28),
('Cosmetology', 'COSMETOLOGY101', 'Hair Styling, Skin Care', 'Ms. Martinez, Mr. Baker', 25),
('Physical Education', 'PHYSICAL_ED102', 'Team Sports, Outdoor Recreation', 'Coach Johnson, Coach Adams', 75),
('French', 'FRENCH101', 'Grammar, Pronunciation, Conversation', 'Mr. Garcia, Ms. Flores', 68),
('German', 'GERMAN101', 'Vocabulary, German Culture', 'Ms. Schmidt, Mr. Wagner', 62),
('Chinese', 'CHINESE101', 'Mandarin Chinese, Chinese Calligraphy', 'Ms. Li, Mr. Zhang', 48),
('Japanese', 'JAPANESE101', 'Hiragana, Katakana, Kanji', 'Ms. Tanaka, Mr. Yamamoto', 55),
('Italian', 'ITALIAN101', 'Italian Cuisine, Italian Opera', 'Ms. Rossi, Mr. Bianchi', 50),
('Russian', 'RUSSIAN101', 'Russian Literature, Russian History', 'Ms. Ivanova, Mr. Petrov', 60),
('Latin', 'LATIN101', 'Latin Grammar, Roman History', 'Ms. Silva, Mr. Santos', 55),
('Arabic', 'ARABIC101', 'Arabic Script, Islamic Civilization', 'Ms. Khalifa, Mr. Ahmed', 52),
('Korean', 'KOREAN101', 'Hangul, Korean Pop Culture', 'Ms. Park, Mr. Kim', 45),
('Swedish', 'SWEDISH101', 'Swedish Language, Scandinavian Culture', 'Ms. Andersson, Mr. Nilsson', 40),
('Portuguese', 'PORTUGUESE101', 'Portuguese Literature, Brazilian Culture', 'Ms. Silva, Mr. Santos', 35),
('Dutch', 'DUTCH101', 'Dutch Art, Dutch Literature', 'Ms. De Vries, Mr. Van Der Meer', 30),
('Greek', 'GREEK101', 'Ancient Greek Philosophy, Greek Mythology', 'Ms. Papadopoulos, Mr. Papadakis', 32),
('Hebrew', 'HEBREW101', 'Biblical Hebrew, Israeli History', 'Ms. Levy, Mr. Cohen', 28),
('Hindi', 'HINDI101', 'Hindi Film, Indian Culture', 'Ms. Patel, Mr. Kumar', 33),
('Thai', 'THAI101', 'Thai Cuisine, Thai Massage', 'Ms. Sriporn, Mr. Boonmee', 40),
('Vietnamese', 'VIETNAMESE101', 'Vietnamese Language, Vietnamese Cuisine', 'Ms. Nguyen, Mr. Tran', 38),
('Indonesian', 'INDONESIAN101', 'Indonesian Art, Indonesian Music', 'Ms. Suryani, Mr. Wijaya', 42),
('Filipino', 'FILIPINO101', 'Filipino Folklore, Philippine History', 'Ms. Santos, Mr. Reyes', 36),
('Malay', 'MALAY101', 'Malay Language, Malay Cuisine', 'Ms. Tan, Mr. Lim', 40),
('Bengali', 'BENGALI101', 'Bengali Literature, Bengali Cuisine', 'Ms. Das, Mr. Chatterjee', 32),
('Punjabi', 'PUNJABI101', 'Punjabi Folk Music, Punjabi Cuisine', 'Ms. Kaur, Mr. Singh', 38),
('Tamil', 'TAMIL101', 'Tamil Cinema, Tamil Culture', 'Ms. Raman, Mr. Kumar', 45),
('Telugu', 'TELUGU101', 'Telugu Literature, Telugu Cinema', 'Ms. Reddy, Mr. Rao', 48),
('Marathi', 'MARATHI101', 'Marathi Theater, Marathi Cuisine', 'Ms. Deshpande, Mr. Patil', 32),
('Gujarati', 'GUJARATI101', 'Gujarati Folk Dance, Gujarati Cuisine', 'Ms. Patel, Mr. Shah', 38),
('Kannada', 'KANNADA101', 'Kannada Poetry, Kannada Films', 'Ms. Rao, Mr. Shetty', 45),
('Malayalam', 'MALAYALAM101', 'Malayalam Literature, Malayalam Cinema', 'Ms. Nair, Mr. Menon', 48),
('Urdu', 'URDU101', 'Urdu Poetry, Urdu Calligraphy', 'Ms. Khan, Mr. Ahmed', 32),
('Sanskrit', 'SANSKRIT101', 'Sanskrit Grammar, Sanskrit Literature', 'Ms. Sharma, Mr. Singh', 38),
('Farsi', 'FARSI101', 'Persian Poetry, Persian Miniatures', 'Ms. Khadem, Mr. Hosseini', 45),
('Turkish', 'TURKISH101', 'Turkish Music, Turkish Cuisine', 'Ms. Yılmaz, Mr. Demir', 48),
('Bulgarian', 'BULGARIAN101', 'Bulgarian Folk Music, Bulgarian Dance', 'Ms. Ivanova, Mr. Petrov', 32),
('Czech', 'CZECH101', 'Czech Literature, Czech History', 'Ms. Nováková, Mr. Svoboda', 38),
('Hungarian', 'HUNGARIAN101', 'Hungarian Folklore, Hungarian Cuisine', 'Ms. Nagy, Mr. Tóth', 45),
('Polish', 'POLISH101', 'Polish Cinema, Polish Literature', 'Ms. Nowak, Mr. Kowalski', 48),
('Romanian', 'ROMANIAN101', 'Romanian Art, Romanian Literature', 'Ms. Ionescu, Mr. Popescu', 32),
('Russian', 'RUSSIAN102', 'Russian Theater, Russian Ballet', 'Ms. Ivanova, Mr. Petrov', 38),
('Serbian', 'SERBIAN101', 'Serbian Folk Music, Serbian Literature', 'Ms. Petrović, Mr. Jovanović', 45),
('Slovak', 'SLOVAK101', 'Slovak Folk Dance, Slovak Cuisine', 'Ms. Nováková, Mr. Kováč', 48),
('Slovenian', 'SLOVENIAN101', 'Slovenian Literature, Slovenian Art', 'Ms. Kovačič, Mr. Novak', 32),
('Ukrainian', 'UKRAINIAN101', 'Ukrainian Dance, Ukrainian Cuisine', 'Ms. Petrova, Mr. Ivanov', 38),
('Armenian', 'ARMENIAN101', 'Armenian Music, Armenian Cuisine', 'Ms. Sarkissian, Mr. Ohanian', 45),
('Georgian', 'GEORGIAN101', 'Georgian Dance, Georgian Cuisine', 'Ms. Javakhishvili, Mr. Kalandadze', 48),
('Kazakh', 'KAZAKH101', 'Kazakh Literature, Kazakh History', 'Ms. Nurmagambetova, Mr. Kozha', 32),
('Uzbek', 'UZBEK101', 'Uzbek Music, Uzbek Cuisine', 'Ms. Akhmedova, Mr. Abdullayev', 38),
('Turkmen', 'TURKMEN101', 'Turkmen Folklore, Turkmen Poetry', 'Ms. Amanova, Mr. Berdiyev', 45),
('Tajik', 'TAJIK101', 'Tajik Literature, Tajik Dance', 'Ms. Rakhimova, Mr. Nazarov', 48),
('Kyrgyz', 'KYRGYZ101', 'Kyrgyz Music, Kyrgyz Cuisine', 'Ms. Ismailova, Mr. Jumabaev', 32),
('Mongolian', 'MONGOLIAN101', 'Mongolian Folk Music, Mongolian Wrestling', 'Ms. Tumur, Mr. Enkhbat', 38),
('Chinese', 'CHINESE102', 'Chinese Poetry, Chinese Opera', 'Ms. Li, Mr. Zhang', 45),
('Japanese', 'JAPANESE102', 'Japanese Literature, Japanese Calligraphy', 'Ms. Tanaka, Mr. Yamamoto', 48),
('Korean', 'KOREAN102', 'Korean Drama, Korean Cuisine', 'Ms. Park, Mr. Kim', 32),
('Arabic', 'ARABIC102', 'Arabic Literature, Arabic Calligraphy', 'Ms. Khalifa, Mr. Ahmed', 38),
('French', 'FRENCH102', 'French Cinema, French Cuisine', 'Ms. Garcia, Mr. Martin', 45),
('German', 'GERMAN102', 'German Philosophy, German Poetry', 'Ms. Müller, Mr. Schmidt', 48),
('Spanish', 'SPANISH102', 'Spanish Literature, Spanish Cuisine', 'Ms. López, Mr. González', 32),
('Italian', 'ITALIAN102', 'Italian Opera, Italian Renaissance', 'Ms. Russo, Mr. Ferrari', 38),
('Russian', 'RUSSIAN103', 'Russian Folklore, Russian Cuisine', 'Ms. Ivanova, Mr. Petrov', 45),
('Portuguese', 'PORTUGUESE102', 'Portuguese Poetry, Portuguese Fado', 'Ms. Silva, Mr. Santos', 48),
('Dutch', 'DUTCH102', 'Dutch Golden Age, Dutch Masters', 'Ms. De Vries, Mr. Van Der Meer', 32),
('Greek', 'GREEK102', 'Greek Mythology, Greek Drama', 'Ms. Papadopoulos, Mr. Papadakis', 38),
('Hebrew', 'HEBREW102', 'Modern Hebrew, Hebrew Literature', 'Ms. Levy, Mr. Cohen', 45),
('Hindi', 'HINDI102', 'Bollywood Films, Hindi Literature', 'Ms. Patel, Mr. Kumar', 48),
('Bengali', 'BENGALI102', 'Bengali Music, Bengali Literature', 'Ms. Das, Mr. Chatterjee', 32),
('Punjabi', 'PUNJABI102', 'Punjabi Folk Dance, Punjabi Cuisine', 'Ms. Kaur, Mr. Singh', 38),
('Tamil', 'TAMIL102', 'Tamil Poetry, Tamil Films', 'Ms. Raman, Mr. Kumar', 45),
('Telugu', 'TELUGU102', 'Telugu Literature, Telugu Cinema', 'Ms. Reddy, Mr. Rao', 48),
('Marathi', 'MARATHI102', 'Marathi Music, Marathi Literature', 'Ms. Deshpande, Mr. Patil', 32),
('Gujarati', 'GUJARATI102', 'Gujarati Theater, Gujarati Cuisine', 'Ms. Patel, Mr. Shah', 38),
('Kannada', 'KANNADA102', 'Kannada Poetry, Kannada Films', 'Ms. Rao, Mr. Shetty', 45),
('Malayalam', 'MALAYALAM102', 'Malayalam Films, Malayalam Literature', 'Ms. Nair, Mr. Menon', 48),
('Urdu', 'URDU102', 'Urdu Ghazals, Urdu Poetry', 'Ms. Khan, Mr. Ahmed', 32),
('Sanskrit', 'SANSKRIT102', 'Sanskrit Drama, Sanskrit Epics', 'Ms. Sharma, Mr. Singh', 38),
('Farsi', 'FARSI102', 'Persian Miniatures, Persian Calligraphy', 'Ms. Khadem, Mr. Hosseini', 45),
('Turkish', 'TURKISH102', 'Turkish Literature, Turkish Cuisine', 'Ms. Yılmaz, Mr. Demir', 48),
('Bulgarian', 'BULGARIAN102', 'Bulgarian Music, Bulgarian Literature', 'Ms. Ivanova, Mr. Petrov', 32),
('Czech', 'CZECH102', 'Czech Cinema, Czech Poetry', 'Ms. Nováková, Mr. Svoboda', 38),
('Hungarian', 'HUNGARIAN102', 'Hungarian Dance, Hungarian Music', 'Ms. Nagy, Mr. Tóth', 45),
('Polish', 'POLISH102', 'Polish Literature, Polish Folk Music', 'Ms. Nowak, Mr. Kowalski', 48),
('Romanian', 'ROMANIAN102', 'Romanian Folklore, Romanian Music', 'Ms. Ionescu, Mr. Popescu', 32),
('Russian', 'RUSSIAN104', 'Russian Film, Russian Music', 'Ms. Ivanova, Mr. Petrov', 38),
('Serbian', 'SERBIAN102', 'Serbian Literature, Serbian Folk Music', 'Ms. Petrović, Mr. Jovanović', 45),
('Slovak', 'SLOVAK102', 'Slovak Theater, Slovak Literature', 'Ms. Nováková, Mr. Kováč', 48),
('Slovenian', 'SLOVENIAN102', 'Slovenian Music, Slovenian Literature', 'Ms. Kovačič, Mr. Novak', 32),
('Ukrainian', 'UKRAINIAN102', 'Ukrainian Literature, Ukrainian Music', 'Ms. Petrova, Mr. Ivanov', 38),
('Armenian', 'ARMENIAN102', 'Armenian Literature, Armenian Music', 'Ms. Sarkissian, Mr. Ohanian', 45),
('Georgian', 'GEORGIAN102', 'Georgian Music, Georgian Literature', 'Ms. Javakhishvili, Mr. Kalandadze', 48),
('Kazakh', 'KAZAKH102', 'Kazakh Literature, Kazakh Music', 'Ms. Nurmagambetova, Mr. Kozha', 32),
('Uzbek', 'UZBEK102', 'Uzbek Literature, Uzbek Music', 'Ms. Akhmedova, Mr. Abdullayev', 38),
('Turkmen', 'TURKMEN102', 'Turkmen Literature, Turkmen Music', 'Ms. Amanova, Mr. Berdiyev', 45),
('Tajik', 'TAJIK102', 'Tajik Literature, Tajik Music', 'Ms. Rakhimova, Mr. Nazarov', 48),
('Kyrgyz', 'KYRGYZ102', 'Kyrgyz Literature, Kyrgyz Music', 'Ms. Ismailova, Mr. Jumabaev', 32),
('Mongolian', 'MONGOLIAN102', 'Mongolian Literature, Mongolian Music', 'Ms. Tumur, Mr. Enkhbat', 38),
('Chinese', 'CHINESE103', 'Chinese Calligraphy, Chinese Philosophy', 'Ms. Li, Mr. Zhang', 45),
('Japanese', 'JAPANESE103', 'Japanese Zen, Japanese Tea Ceremony', 'Ms. Tanaka, Mr. Yamamoto', 48),
('Korean', 'KOREAN103', 'Korean Literature, Korean Cinema', 'Ms. Park, Mr. Kim', 32),
('Arabic', 'ARABIC103', 'Arabic Calligraphy, Islamic Art', 'Ms. Khalifa, Mr. Ahmed', 38),
('French', 'FRENCH103', 'French Poetry, French Revolution', 'Ms. Garcia, Mr. Martin', 45),
('German', 'GERMAN103', 'German Opera, German Expressionism', 'Ms. Müller, Mr. Schmidt', 48),
('Spanish', 'SPANISH103', 'Spanish Cinema, Spanish Guitar', 'Ms. López, Mr. González', 32),
('Italian', 'ITALIAN103', 'Italian Renaissance Art, Italian Opera', 'Ms. Russo, Mr. Ferrari', 38),
('Russian', 'RUSSIAN105', 'Russian Literature, Russian Folk Music', 'Ms. Ivanova, Mr. Petrov', 45),
('Portuguese', 'PORTUGUESE103', 'Portuguese Fado, Portuguese Literature', 'Ms. Silva, Mr. Santos', 48),
('Dutch', 'DUTCH103', 'Dutch Masters, Dutch Golden Age', 'Ms. De Vries, Mr. Van Der Meer', 32),
('Greek', 'GREEK103', 'Greek Drama, Greek Philosophy', 'Ms. Papadopoulos, Mr. Papadakis', 38),
('Hebrew', 'HEBREW103', 'Hebrew Bible, Modern Hebrew Literature', 'Ms. Levy, Mr. Cohen', 45),
('Hindi', 'HINDI103', 'Hindi Literature, Indian Cinema', 'Ms. Patel, Mr. Kumar', 48),
('Bengali', 'BENGALI103', 'Bengali Poetry, Bengali Folk Music', 'Ms. Das, Mr. Chatterjee', 32),
('Punjabi', 'PUNJABI103', 'Punjabi Literature, Punjabi Folk Music', 'Ms. Kaur, Mr. Singh', 38),
('Tamil', 'TAMIL103', 'Tamil Films, Tamil Literature', 'Ms. Raman, Mr. Kumar', 45),
('Telugu', 'TELUGU103', 'Telugu Cinema, Telugu Literature', 'Ms. Reddy, Mr. Rao', 48),
('Marathi', 'MARATHI103', 'Marathi Literature, Marathi Folk Music', 'Ms. Deshpande, Mr. Patil', 32),
('Gujarati', 'GUJARATI103', 'Gujarati Literature, Gujarati Folk Music', 'Ms. Patel, Mr. Shah', 38),
('Kannada', 'KANNADA103', 'Kannada Cinema, Kannada Literature', 'Ms. Rao, Mr. Shetty', 45),
('Malayalam', 'MALAYALAM103', 'Malayalam Literature, Malayalam Cinema', 'Ms. Nair, Mr. Menon', 48),
('Urdu', 'URDU103', 'Urdu Literature, Urdu Ghazals', 'Ms. Khan, Mr. Ahmed', 32),
('Sanskrit', 'SANSKRIT103', 'Sanskrit Epics, Sanskrit Poetry', 'Ms. Sharma, Mr. Singh', 38),
('Farsi', 'FARSI103', 'Persian Literature, Persian Poetry', 'Ms. Khadem, Mr. Hosseini', 45),
('Turkish', 'TURKISH103', 'Turkish Literature, Turkish Folk Music', 'Ms. Yılmaz, Mr. Demir', 48),
('Bulgarian', 'BULGARIAN103', 'Bulgarian Folk Music, Bulgarian Literature', 'Ms. Ivanova, Mr. Petrov', 32),
('Czech', 'CZECH103', 'Czech Literature, Czech Music', 'Ms. Nováková, Mr. Svoboda', 38),
('Hungarian', 'HUNGARIAN103', 'Hungarian Literature, Hungarian Music', 'Ms. Nagy, Mr. Tóth', 45),
('Polish', 'POLISH103', 'Polish Folk Music, Polish Literature', 'Ms. Nowak, Mr. Kowalski', 48),
('Romanian', 'ROMANIAN103', 'Romanian Folk Music, Romanian Literature', 'Ms. Ionescu, Mr. Popescu', 32),
('Russian', 'RUSSIAN106', 'Russian Folk Dance, Russian Literature', 'Ms. Ivanova, Mr. Petrov', 38),
('Serbian', 'SERBIAN103', 'Serbian Literature, Serbian Folk Dance', 'Ms. Petrović, Mr. Jovanović', 45),
('Slovak', 'SLOVAK103', 'Slovak Literature, Slovak Folk Music', 'Ms. Nováková, Mr. Kováč', 48),
('Slovenian', 'SLOVENIAN103', 'Slovenian Literature, Slovenian Music', 'Ms. Kovačič, Mr. Novak', 32),
('Ukrainian', 'UKRAINIAN103', 'Ukrainian Literature, Ukrainian Folk Music', 'Ms. Petrova, Mr. Ivanov', 38),
('Armenian', 'ARMENIAN103', 'Armenian Literature, Armenian Music', 'Ms. Sarkissian, Mr. Ohanian', 45),
('Georgian', 'GEORGIAN103', 'Georgian Literature, Georgian Music', 'Ms. Javakhishvili, Mr. Kalandadze', 48),
('Kazakh', 'KAZAKH103', 'Kazakh Literature, Kazakh Folk Music', 'Ms. Nurmagambetova, Mr. Kozha', 32),
('Uzbek', 'UZBEK103', 'Uzbek Literature, Uzbek Folk Music', 'Ms. Akhmedova, Mr. Abdullayev', 38),
('Turkmen', 'TURKMEN103', 'Turkmen Literature, Turkmen Folk Music', 'Ms. Amanova, Mr. Berdiyev', 45),
('Tajik', 'TAJIK103', 'Tajik Literature, Tajik Music', 'Ms. Rakhimova, Mr. Nazarov', 48),
('Kyrgyz', 'KYRGYZ103', 'Kyrgyz Literature, Kyrgyz Folk Music', 'Ms. Ismailova, Mr. Jumabaev', 32),
('Mongolian', 'MONGOLIAN103', 'Mongolian Literature, Mongolian Folk Music', 'Ms. Tumur, Mr. Enkhbat', 38);




